### ISSUE TITLE
Resize atlas

### ISSUE THREAD

**Issue by grovesNL** [nical/etagere#22]
Could we add a way to resize an atlas, ideally keeping any existing allocation locations?

**Comment by nical** [comment]
I think that it would be valuable and not too difficult to allow growing the atlas (shrinking less so, but perhaps not as useful in practice). I am very short on spare time right now so I might not be able to put that together soon. Are you only interested in the bucketed allocator?

**Comment by grovesNL** [comment]
Ok sounds great. I'm just interested in the `BucketedAtlasAllocator` for now.

No rush on the timing - I'd also be happy to try to implement it.
