### ISSUE TITLE
Please change the RectangleBinPack link in the document.

### ISSUE THREAD

**Issue by km19809** [nical/etagere#25]
This is a very awkward issue, however, I must report it.
This library has an Egloos link in the document. [(lib.rs)](https://github.com/nical/etagere/blob/02d33ca14c845ced507d429e9f1805fd5525d29b/src/lib.rs#L11)
However, Egloos, a Korean blog service, will be closed after Dec. 18. [Announcement in Korean](https://egloosbackup.egloos.com/)
Please replace the link with [the author's pdf](https://github.com/juj/RectangleBinPack/blob/master/RectangleBinPack.pdf).

**Comment by nical** [comment]
Thanks for the heads up!

**Comment by km19809** [comment]
Closed with 95d6f37
