### ISSUE TITLE
Questions about the use of `i32`

### ISSUE THREAD

**Issue by ztlwk** [nical/etagere#29]
I am curious about the why `Size` and many other related types use signed int.
Should it be the `u32` or I had gotten anything wrong? The type used to describe sizes of textures in wgpu is `u32`.

**Comment by nical** [comment]
Well, etagere isn't tied to wgpu, both projects make their own independent choices (in wgpu's case it inherits its choices from the WebGPU specification).

Some people argue that using unsigned integers everywhere increases the risks of integer underflows, I err on that side. I tend to pick signed integers by default for things that I do arithmetic on (typically, coordinates and by extension, sizes of things these coordinates fit in). Would you use an unsigned floating point number type if it existed? I don't think I would.

**Comment by ztlwk** [comment]
I just want to confirm that the crate does not rely on negative values because I didn't find any so far.
BTW, Rust can panic when overflowing in some cases, and there is also checked arithmetic available for `u32`.

**Comment by ztlwk** [comment]
I just want to confirm that the crate does not rely on negative values because I didn't find any so far.
BTW, Rust will check for overflow or panic in some cases, and there is also checked arithmetic available for `u32`.

**Comment by nical** [comment]
The crate does not rely on negative values. I think that answers your questions, so I'm going to close this  but feel free to ask followups here if you have other questions.
