### ISSUE TITLE
Merge with guillotière crate?

### ISSUE THREAD

**Issue by dhardy** [nical/etagere#7]
Motivation: where the extra functionality of guillotière is not used (I think just rearranging, though that could be an empty op for étagère), it would be possible to abstract over the allocator with a trait — `A: AtlasAllocator` or `Box<dyn AtlasAllocator>`.

In practice one may still end up using (e.g.) only étagère for glyphs and guillotière for images, but more code share for texture atlas management is possible.

**Comment by nical** [comment]
I prefer to keep the two crates independent (although I make an effort to make the APIs similar), for the sake of clean and small dependencies. There isn't code to be shared between the two and it's rather effortless to abstract over the allocators in you own code, for example I do it here https://github.com/nical/texture-atlas/blob/7d1be4b40f5c46b673a3b57390d127aa5b56786b/src/lib.rs#L74 And similarly in webrender here https://github.com/servo/webrender/blob/27047062dd47068b2eb66c89b986c8a5aed532c2/webrender/src/texture_pack/mod.rs#L30

Perhaps that could be done in yet another crate if there is some extra value to get from it like higher level logic dealing with multiple textures or caching/eviction features, but the trait alone is easy enough to write and customize for to each project's specific needs that I wouldn't bother making a crate just for it.

**Comment by dhardy** [comment]
I guess that's a fair argument (although each crate is quite small anyway).

A significant part of the public API (if one includes the Euclid re-exports) is shared, but this is still not much code.

Anyway, thanks for the crates!
